### PR TITLE
Added hashtags to messages to allow easy search

### PR DESCRIPTION
**Pull request by mhverbakel**
By adding hashtags to these messages, the pollslist command becomes obsolete. It also allows easy search in groups with big volume.

### CODE REVIEW

**Comment by worried-networking** [comment]
Thank you for your time! But I think it should be done in another way: those tags shouldn't be messed with translations, but there is should be an option in bot's settings (we need more strange options!! :)) which is responsible for automatic appending those tags to the message in any language.

**Comment by mhverbakel** [comment]
Ah okay, I am not capable to do that, sorry.

**Comment by worried-networking** [comment]
Yeah, I remember :) It's a good idea and it's should be easy to implement it, so I'll do it in a few days.

**Comment by worried-networking** [comment]
Enable hashtags by sending `/toggletagpolls`

**Comment by mhverbakel** [comment]
Thank you, amazing! 😄

**Pull request closed without merging**
